### ISSUE TITLE
Could you add a procedure for using this specific blueprint?

### ISSUE THREAD

**Issue by paaljoachim** [ServerPress/wordpress-latest#2]
Hi

Thanks for creating this blueprint!..:)

I downloaded the zip and placed it into the blueprints folder and then tried to make a new site using it.
It opened a directory folder instead of a new site install procedure. So obviously I am doing something wrong.

I have no idea if WP-CLI is active which probably means it is not.
How do I activate WP-CLI?

Btw
Creating user defined templates one can use to install a new site is something I very much look forward to. There are so many possibilities with this!

Have a great day!

**Comment by Steveorevo** [comment]
Are you running the latest DesktopServer 3.8.2 (it comes with WP-CLI in DS-CLI). For more information please visit: 

https://serverpress.com/desktopserver-ds-cli-command-line-interface/

**Comment by paaljoachim** [comment]
I was running version 3.8.1 and logged into my account at Serverpress and downloaded the newest version 3.8.2. Checked the link you shared and am now up and running with WPCLI. Thanks Steve!
